name: islamic_heroes_app
description: "The Islamic Heroes App is an interactive and educational application designed to educate users about significant figures in Islamic history, including companions, scholars, and military leaders. The app will deliver a rich multimedia experience, offering biographies, achievements, and historical impacts of these figures. Users will have access to interactive features such as quizzes, daily notifications, and tailored content to enhance their learning experience"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true  # Add this line

  # assets:
