// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWfyc-aHotT7QzUiWxomtRZRmd6morp8',
    appId: '1:833831555627:web:951abcc4ab26eb8a80906e',
    messagingSenderId: '833831555627',
    projectId: 'islamic-heroes-app',
    authDomain: 'islamic-heroes-app.firebaseapp.com',
    storageBucket: 'islamic-heroes-app.firebasestorage.app',
    measurementId: 'G-ZG9HS3LLQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHwDRD5Y0CT1O8vTLMNu8kk61IgtN4gPY',
    appId: '1:833831555627:android:01bc5dc273357ad280906e',
    messagingSenderId: '833831555627',
    projectId: 'islamic-heroes-app',
    storageBucket: 'islamic-heroes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXWiEj0jsvAuICGHsaGIi7QhPpIkrZtuc',
    appId: '1:833831555627:ios:8780b7282e1244ff80906e',
    messagingSenderId: '833831555627',
    projectId: 'islamic-heroes-app',
    storageBucket: 'islamic-heroes-app.firebasestorage.app',
    iosClientId: '833831555627-rorton2ckof2vqv2orisgv8rbcnsd15k.apps.googleusercontent.com',
    iosBundleId: 'com.example.islamicHeroesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXWiEj0jsvAuICGHsaGIi7QhPpIkrZtuc',
    appId: '1:833831555627:ios:8780b7282e1244ff80906e',
    messagingSenderId: '833831555627',
    projectId: 'islamic-heroes-app',
    storageBucket: 'islamic-heroes-app.firebasestorage.app',
    iosClientId: '833831555627-rorton2ckof2vqv2orisgv8rbcnsd15k.apps.googleusercontent.com',
    iosBundleId: 'com.example.islamicHeroesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMWfyc-aHotT7QzUiWxomtRZRmd6morp8',
    appId: '1:833831555627:web:61773e221f48994880906e',
    messagingSenderId: '833831555627',
    projectId: 'islamic-heroes-app',
    authDomain: 'islamic-heroes-app.firebaseapp.com',
    storageBucket: 'islamic-heroes-app.firebasestorage.app',
    measurementId: 'G-1FD17MKM0F',
  );

}